name       : gamehub
version    : 0.14.2_1
release    : 2
source     :
    - https://github.com/tkashkin/GameHub/archive/0.14.2-1-master.tar.gz : fe230da7ab63211ba08b5b84fda8633784e3e503b71dc432096ee315d6b15dae
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure -Dgit_branch=master
build      : |
    %ninja_build
install    : |
    %ninja_install
