name       : gamehub
version    : 0.16.2_1
release    : 6
source     :
    - https://github.com/tkashkin/GameHub/archive/refs/tags/0.16.2-1-dev.tar.gz : 9acbc8eae604b434750788977e2d3570f6791ee54402a3c43f703394d9d4fd87
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure -Dgit_branch=master
build      : |
    %ninja_build
install    : |
    %ninja_install
