name       : gamehub
version    : 0.16.1_2
release    : 5
source     :
    - https://github.com/tkashkin/GameHub/archive/refs/tags/0.16.1-2-master.tar.gz : bbbf2f5216ce6f0d6a57179f388a714aec52188f4e67a9deb6478061441a30b5
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure -Dgit_branch=master
build      : |
    %ninja_build
install    : |
    %ninja_install
