name       : gamehub
version    : 0.16.3_2
release    : 7
source     :
    - https://github.com/tkashkin/GameHub/archive/refs/tags/0.16.3-2-master.tar.gz : 3ff1fcb22342f3327f56278587c9ed7eb26fba8d56bb295ac7ed7dd80d5d5b9a
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure -Dgit_branch=master
build      : |
    %ninja_build
install    : |
    %ninja_install
