name       : gamehub
version    : 0.15.0_1
release    : 3
source     :
    - https://github.com/tkashkin/GameHub/archive/0.15.0-1-master.tar.gz : 0182a32b595451b6bebf6f8173b6a41690e1c2b2d1c0b1a07cfce2ea0e536302
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure -Dgit_branch=master
build      : |
    %ninja_build
install    : |
    %ninja_install
