name       : gamehub
version    : 0.16.0_1
release    : 4
source     :
    - https://github.com/tkashkin/GameHub/archive/0.16.0-1-master.tar.gz : 4244c914d7427933727ec0611886720b9325c4d4a852e0e8c283f6331ebd30e2
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure -Dgit_branch=master
build      : |
    %ninja_build
install    : |
    %ninja_install
