name       : gamehub
version    : 0.14.1_2
release    : 1
source     :
    - https://github.com/tkashkin/GameHub/archive/0.14.1-2-master.tar.gz : 3f4c77dc3d65adab293ee0ac209f111e077e5d0a6c0800d031f11cc3056325b7
license    : GPL-3.0-or-later
component  : games
summary    : Unified library for all your games
description: |
    GameHub allows to view, download, install, run and uninstall games from multiple sources.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    git_commit=a82e30a648c20624aa74dee0ea2ce802bc66887a

    %meson_configure -D git_branch=master \
        -D git_commit=$git_commit \
        -Dgit_commit_short=${git_commit:0:7}
build      : |
    %ninja_build
install    : |
    %ninja_install
